# this is a java project using maven
language: java
jdk:
# oracle jdk8 and jdk9 does not work on default dist
#  - oraclejdk8
#  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk-ea
# switch off gpg handling, javadoc and tests
install: 
   - mvn install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true
script: 
   - mvn test -Dtest=com.blazegraph.gremlin.structure.SampleCode
   - mvn test -Dtest=com.blazegraph.gremlin.structure.TestSearch
