# this is a java project using maven
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk-ea
# switch off gpg handling and javadoc
#install: mvn install -Dmaven.javadoc.skip=true -Dgpg.skip=true
install: mvn install -Dtest=SampleCode -Dmaven.javadoc.skip=true -Dgpg.skip=true

