#!/bin/bash
LC_NUMERIC="en_US.UTF-8"
TIMES=()
PACKAGES=()
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true
for package in TestBasicOperations TestBulkLoad TestHistory TestSearch SampleCode TestSearch
do
  START=$(date +%s.%N)
  mvn test -Dtest=com.blazegraph.gremlin.structure.$package
  END=$(date +%s.%N)
  DIFF=$(echo "$END - $START" | bc)
  TIMES+=($DIFF)
  PACKAGES+=($package)
done
# get length of an array
len=${#PACKAGES[@]}
for (( i=1; i<${len}+1; i++ ));
do
   package=${PACKAGES[$i-1]}
   DIFF=${TIMES[$i-1]}
   printf "%2d/%2d testing %20s took %.1f secs\n" $i $len $package $DIFF
done
